# Starter pipeline with Resource Creation
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # Replace with your Azure Subscription ID
  azureSubscriptionId: 'your-azure-subscription-id'
  resourceGroupName: 'abcRG'
  location: 'eastus'  # Replace with desired location

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy Storage Account'
    inputs:
      azureSubscriptionId: ${{ variables.azureSubscriptionId }}
      action: 'CreateOrUpdate'
      resourceGroupName: ${{ variables.resourceGroupName }}
      location: ${{ variables.location }}
      templateLocation: 'linkedFile'
      templateFile: 'azuredeploy.json'  # Replace with your ARM template file path

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'