 # YAML Pipeline Definition

  trigger:
    - main

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    azureSubscriptionId: '7232b02a-48c6-4a31-9fa8-014dc71bb52c'
    resourceGroupName: 'MyResourceGroup'
    location: 'eastus'  # Replace with desired location

  steps:
    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: ${{ variables.azureSubscription }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u ${{ secrets.azureServicePrincipalAppId }} -p ${{ secrets.azureServicePrincipalPassword }} -t ${{ secrets.azureTenantId }}

    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: ${{ variables.azureSubscription }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name ${{ variables.resourceGroupName }} --location ${{ variables.location }}