# Starter pipeline with Resource Creation
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # Replace with your Azure Subscription ID
  azureSubscriptionId: '7232b02a-48c6-4a31-9fa8-014dc71bb52c'
  resourceGroupName: 'TestADORG'
  location: 'eastus'  # Replace with desired location

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy Storage Account'
    inputs:
      connectedServiceName: 'ADOAPPRegistration'  # Replace with your service connection name
      azureSubscriptionId: ${{ variables.azureSubscriptionId }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ variables.resourceGroupName }}
      location: ${{ variables.location }}
      templateLocation: 'Inline template'  # Changed to Inline template
      templateFile: |
        {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": [
            {
              "type": "Microsoft.Storage/storageAccounts",
              "apiVersion": "2019-06-01",
              "name": "[concat('st', uniqueString(resourceId('Microsoft.ResourceGroups/resourceGroups/', variables('resourceGroupName'))))]",
              "location": "[variables('location')]",
              "sku": {
                "name": "Standard_LRS",
                "tier": "Standard",
                "replicationType": "LRS"
              }
            }
          ],
          "variables": {
            "resourceGroupName": "[variables('resourceGroupName')]",
            "location": "[variables('location')]"
          }
        }

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a 1  multi-line script'