trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Visual Studio Professional Subscription'
  resourceGroupName: 'MyNewResourceGroup'
  location: 'eastus'  # Replace with desired location

steps:
  - task: AzureCLI@2
    displayName: 'Login to Azure'
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      scriptType: 'bash'
      inlineScript: |
        az login --service-principal -u ${{ secrets.azureServicePrincipalAppId }} -p ${{ secrets.azureServicePrincipalPassword }} -t ${{ secrets.azureTenantId }}
        echo "Login successful"

  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy Resource Group'
    inputs:
      connectedServiceName: 'ADOAPPRegistration1'
      azureSubscriptionId: ${{ variables.azureSubscriptionId }}
      action: 'Deploy'
      resourceGroupName: ${{ variables.resourceGroupName }}
      location: ${{ variables.location }}
      templateLocation: 'linkedTemplate'
      template: |
        {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": [
            {
              "type": "Microsoft.Resources/resourceGroups",
              "apiVersion": "2019-10-01",
              "name": "[parameters('resourceGroupName')]",
              "location": "[parameters('location')]"
            }
          ],
          "parameters": {
            "resourceGroupName": {
              "type": "string"
            },
            "location": {
              "type": "string"
            }
          }
        }